/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import interfaz.IGestionProveedor;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Estado;
import modelo.Proveedor;
import modelo.Tecnico;
import presentador.PresentadorGestorProveedor;

/**
 *
 * @author USUARIO
 */
public class VistaGestionProveedor extends javax.swing.JFrame implements IGestionProveedor {
    private PresentadorGestorProveedor presentador;

    /**
     * Creates new form VistaRegistrarProovedor
     */
    public VistaGestionProveedor() {
        initComponents();
        this.setLocationRelativeTo(null);
        presentador = new PresentadorGestorProveedor(this);
        presentador.leerProveedores();
    }
    
    public void llenarTablaProveedores(ArrayList<Proveedor> proveedores, ArrayList<Estado> estados, ArrayList<String> direcciones, double[] calificaciones){
        DefaultTableModel model1 = new DefaultTableModel();
        model1.addColumn("DNI");
        model1.addColumn("Apellido");
        model1.addColumn("Nombre");
        model1.addColumn("Direccion");
        model1.addColumn("Telefono");
        model1.addColumn("Estado");
        tablaTecnicos.setModel(model1);
        
        
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("CUIT");
        model.addColumn("Razón Social");
        model.addColumn("Dirección");
        model.addColumn("Telefono");
        model.addColumn("Calificacion");
        model.addColumn("Estado");
        
        for(int i = 0; i < proveedores.size(); i++){
            model.addRow(new Object[]{
                proveedores.get(i).getCuit(), 
                proveedores.get(i).getRazonSocial(), 
                direcciones.get(i), 
                proveedores.get(i).getTelefono(), 
                calificaciones[i]+"", 
                estados.get(i).getEstado()
            });
        }
        
        jTable1.setModel(model);
    }

    public void llenarTablaTecnicos(ArrayList<Tecnico> tecnicos, ArrayList<Estado> estados, ArrayList<String> direcciones){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("DNI");
        model.addColumn("Apellido");
        model.addColumn("Nombre");
        model.addColumn("Direccion");
        model.addColumn("Telefono");
        model.addColumn("Estado");
        
        for(int i = 0; i < tecnicos.size(); i++){
            model.addRow(new Object[]{
                tecnicos.get(i).getDNI(), 
                tecnicos.get(i).getApellido(), 
                tecnicos.get(i).getNombre(), 
                direcciones.get(i), 
                tecnicos.get(i).getTelefono(), 
                estados.get(i).getEstado()
            });
        }
        
        tablaTecnicos.setModel(model);
    }
    
    public void mostrarMje(String mje){
        JOptionPane.showMessageDialog(null, mje);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaTecnicos = new javax.swing.JTable();
        btnSalir = new javax.swing.JButton();
        lblIncidencias = new javax.swing.JButton();
        lblAgregarTecnico = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtBuscar = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Técnicos Asociados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Microsoft JhengHei Light", 1, 14))); // NOI18N

        tablaTecnicos.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 12)); // NOI18N
        tablaTecnicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "DNI", "Apellido", "Nombres", "Dirección ", "Teléfono", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaTecnicos.setCellSelectionEnabled(true);
        tablaTecnicos.setGridColor(new java.awt.Color(0, 0, 0));
        tablaTecnicos.setSelectionBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tablaTecnicos);
        tablaTecnicos.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 830, 160));

        btnSalir.setBackground(new java.awt.Color(133, 0, 0));
        btnSalir.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 590, 110, 30));

        lblIncidencias.setBackground(new java.awt.Color(0, 0, 0));
        lblIncidencias.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblIncidencias.setForeground(new java.awt.Color(255, 255, 255));
        lblIncidencias.setText("Cantidad de Incidencias");
        lblIncidencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblIncidenciasMouseClicked(evt);
            }
        });
        lblIncidencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblIncidenciasActionPerformed(evt);
            }
        });
        getContentPane().add(lblIncidencias, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 220, 30));

        lblAgregarTecnico.setBackground(new java.awt.Color(0, 0, 0));
        lblAgregarTecnico.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblAgregarTecnico.setForeground(new java.awt.Color(255, 255, 255));
        lblAgregarTecnico.setText("Agregar Técnico");
        lblAgregarTecnico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblAgregarTecnicoMouseClicked(evt);
            }
        });
        lblAgregarTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblAgregarTecnicoActionPerformed(evt);
            }
        });
        getContentPane().add(lblAgregarTecnico, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 520, 200, 30));

        jTable1.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "CUIT", "Nombre/Razón Social", "Dirección", "Teléfono", "Calificación", "Estado"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 870, 150));
        getContentPane().add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 380, 30));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, 110, -1));

        btnModificar.setBackground(new java.awt.Color(0, 0, 0));
        btnModificar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(255, 255, 255));
        btnModificar.setText("Modificar");
        btnModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificarMouseClicked(evt);
            }
        });
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 130, 110, 30));

        btnEliminar.setBackground(new java.awt.Color(0, 0, 0));
        btnEliminar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 130, 100, 30));

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/proveedores.png"))); // NOI18N
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        btnAtras.setBackground(new java.awt.Color(153, 153, 153));
        btnAtras.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 18)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 590, 110, 30));

        btnBuscar.setBackground(new java.awt.Color(0, 0, 0));
        btnBuscar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMouseClicked(evt);
            }
        });
        getContentPane().add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 110, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 938, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
    System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        VistaRegistroPro registropro = new VistaRegistroPro();
        registropro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarMouseClicked

    private void btnModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificarMouseClicked
    
        if (jTable1.getSelectedRow()>=0){
            int rowIndex = jTable1.getSelectedRow();
            VistaModificarPro modificarpro = new VistaModificarPro();
            modificarpro.setVisible(true);
            modificarpro.buscarProveedor((long) jTable1.getValueAt(rowIndex, 0));
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(this,"No ha seleccionado ningún proveedor");
        }
        
        
    }//GEN-LAST:event_btnModificarMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
        VistaMenu menu = new VistaMenu();
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        if (jTable1.getSelectedRow()>=0){
            int rowIndex = jTable1.getSelectedRow();
            long cuit = (long) jTable1.getValueAt(rowIndex, 0);
            presentador.leerTecnicos(cuit);
        }else{
            JOptionPane.showMessageDialog(this,"No ha seleccionado ningún proveedor");
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void lblAgregarTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblAgregarTecnicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblAgregarTecnicoActionPerformed

    private void lblAgregarTecnicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAgregarTecnicoMouseClicked
        // TODO add your handling code here:
        if (jTable1.getSelectedRow()>=0){
            int rowIndex = jTable1.getSelectedRow();
            long cuit = (long) jTable1.getValueAt(rowIndex, 0);
            VistaRegistroTec vistaRegistroTec = new VistaRegistroTec();
            vistaRegistroTec.setVisible(true);
            vistaRegistroTec.setCuitProveedor(cuit);
        }else{
            JOptionPane.showMessageDialog(this,"No ha seleccionado ningún proveedor");
        }
    }//GEN-LAST:event_lblAgregarTecnicoMouseClicked

    private void btnBuscarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMouseClicked
        // TODO add your handling code here:
        try {
            long cuit = Long.parseLong(txtBuscar.getText());
            presentador.buscarProveedor(cuit);
        }
        catch(Exception e) {
            this.mostrarMje("Error en el CUIT o no existe el proveedor");
        }
    }//GEN-LAST:event_btnBuscarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()>=0){
            int rowIndex = jTable1.getSelectedRow();
            long cuit = (long) jTable1.getValueAt(rowIndex, 0);
            //presentador.buscarProveedor(dni);
            int opc = JOptionPane.showConfirmDialog(null, "¿Está seguro de eliminar el proveedor seleccionado?");
            if(opc == 0){
                presentador.eliminarProveedor(cuit);
            }
            
        } else {
            this.mostrarMje("No ha seleccionado ningun técnico");
        }
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void lblIncidenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblIncidenciasMouseClicked
        // TODO add your handling code here:
        presentador.generarReporte();
    }//GEN-LAST:event_lblIncidenciasMouseClicked

    private void lblIncidenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblIncidenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblIncidenciasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaGestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaGestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaGestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaGestionProveedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaGestionProveedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton lblAgregarTecnico;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JButton lblIncidencias;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tablaTecnicos;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
