/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author USUARIO
 */
public class VistaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VistaMenu
     */
    public VistaMenu() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProovedores = new javax.swing.JButton();
        lblTecnicos = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblListar = new javax.swing.JButton();
        lblRecepcion = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblProovedores.setBackground(new java.awt.Color(0, 0, 0));
        lblProovedores.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        lblProovedores.setForeground(new java.awt.Color(255, 255, 255));
        lblProovedores.setText("Gestión de Proveedores");
        lblProovedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProovedoresMouseClicked(evt);
            }
        });
        getContentPane().add(lblProovedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, 360, 40));

        lblTecnicos.setBackground(new java.awt.Color(0, 0, 0));
        lblTecnicos.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        lblTecnicos.setForeground(new java.awt.Color(255, 255, 255));
        lblTecnicos.setText("Gestión de Técnicos");
        lblTecnicos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTecnicosMouseClicked(evt);
            }
        });
        getContentPane().add(lblTecnicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 360, 40));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo mediano.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 310, 240));

        lblListar.setBackground(new java.awt.Color(0, 0, 0));
        lblListar.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        lblListar.setForeground(new java.awt.Color(255, 255, 255));
        lblListar.setText("Listado de Proveedores, Técnicos y Equipos");
        lblListar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblListarMouseClicked(evt);
            }
        });
        getContentPane().add(lblListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 360, 40));

        lblRecepcion.setBackground(new java.awt.Color(0, 0, 0));
        lblRecepcion.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 16)); // NOI18N
        lblRecepcion.setForeground(new java.awt.Color(255, 255, 255));
        lblRecepcion.setText("Recepción de Equipos");
        lblRecepcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRecepcionMouseClicked(evt);
            }
        });
        getContentPane().add(lblRecepcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 480, 360, 40));

        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/muñecosi.png"))); // NOI18N
        getContentPane().add(lblIcono, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, 90, 370, 400));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblProovedoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProovedoresMouseClicked
    VistaGestionProveedor gestionProovedor=new VistaGestionProveedor();
    gestionProovedor.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_lblProovedoresMouseClicked

    private void lblTecnicosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTecnicosMouseClicked
    VistaGestionTecnico gestionTecnico = new VistaGestionTecnico();
    gestionTecnico.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_lblTecnicosMouseClicked

    private void lblListarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblListarMouseClicked
    VistaListado listado = new VistaListado();
    listado.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_lblListarMouseClicked

    private void lblRecepcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRecepcionMouseClicked
    VistaRecepcion recepcion = new VistaRecepcion();
    recepcion.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_lblRecepcionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JButton lblListar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JButton lblProovedores;
    private javax.swing.JButton lblRecepcion;
    private javax.swing.JButton lblTecnicos;
    // End of variables declaration//GEN-END:variables
}
