/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import interfaz.IGestionTecnicoAg;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Estado;
import modelo.Localidad;
import modelo.Pais;
import modelo.Provincia;
import presentador.PresentadorGestorTecnicoAg;

/**
 *
 * @author USUARIO
 */
public class VistaRegistroTec extends javax.swing.JFrame implements IGestionTecnicoAg{
    private PresentadorGestorTecnicoAg presentador;
    /**
     * Creates new form VistaRegistroPro
     */
    public VistaRegistroTec() {
        initComponents();
        this.setLocationRelativeTo(null);
        presentador = new PresentadorGestorTecnicoAg(this);
        presentador.cargarListaPais();
        presentador.cargarListaEstado();
    }
    
    public void setCuitProveedor(long cuit){txtCUIT.setText(cuit+"");}
    
    @Override
    public void cargarListaPais(ArrayList<Pais> paises) {
        cmbPais.removeAllItems();
        for(Pais pais : paises){
            cmbPais.addItem(pais.getNombre());
        }
        cmbPais.setSelectedIndex(0);
    }

    @Override
    public void cargarListaProvincia(ArrayList<Provincia> provincias) {
        cmbProvincia.removeAllItems();
        for(Provincia prov : provincias){
            cmbProvincia.addItem(prov.getNombre());
        }
        cmbProvincia.setSelectedIndex(0);
    }

    @Override
    public void cargarListaLocalidad(ArrayList<Localidad> localidades){
        cmbLocalidad.removeAllItems();
        for(Localidad l : localidades){
            cmbLocalidad.addItem(l.getNombre());
        }
        cmbLocalidad.setSelectedIndex(0);
    }
    
    @Override
    public void cargarListaEstado(ArrayList<Estado> estados){
        cmbEstado.removeAllItems();
        for(Estado est : estados){
            cmbEstado.addItem(est.getEstado());
        }
        cmbEstado.setSelectedIndex(0);
    }
    
    @Override
    public void mostrarMje(String mje){
        JOptionPane.showMessageDialog(null, mje);
    }
    
    public void cerrar(){
        VistaGestionTecnico gestiontec = new VistaGestionTecnico();
        gestiontec.setVisible(true);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblCuit = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblProvincia = new javax.swing.JLabel();
        lblLocalidad = new javax.swing.JLabel();
        lblCalle = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        txtCUIT = new javax.swing.JTextField();
        txtDni = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbPais = new javax.swing.JComboBox<>();
        cmbLocalidad = new javax.swing.JComboBox<>();
        txtCalle = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        lblDni = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cmbProvincia = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/registrotec.png"))); // NOI18N
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        lblCuit.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblCuit.setText("CUIT PROVEEDOR:");
        getContentPane().add(lblCuit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, -1, 30));

        lblEstado.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblEstado.setText("Estado:");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, -1, 30));

        lblNombre.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 90, 30));

        lblPais.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblPais.setText("País:");
        getContentPane().add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, -1, 30));

        lblProvincia.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblProvincia.setText("Provincia:");
        getContentPane().add(lblProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, 30));

        lblLocalidad.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblLocalidad.setText("Localidad:");
        getContentPane().add(lblLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, 30));

        lblCalle.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblCalle.setText("Calle:");
        getContentPane().add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, -1, 30));

        lblNumero.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblNumero.setText("N°:");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 400, -1, 30));

        lblTelefono.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblTelefono.setText("Teléfono:");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, -1, 30));

        btnSalir.setBackground(new java.awt.Color(149, 0, 0));
        btnSalir.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 570, 80, -1));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 490, 130, -1));

        txtCUIT.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtCUIT, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 110, 140, 30));

        txtDni.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 240, 30));

        cmbEstado.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Inhabilitado" }));
        getContentPane().add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 150, 210, 30));

        cmbPais.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cmbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Bolivia", "Brasil", "Chile ", "Colombia", "Costa Rica ", "Cuba", "Ecuador", "El Salvador ", "Guatemala", "Honduras ", "México", "Nicaragua", "Panamá", "Paraguay", "Perú", "Puerto Rico", "República Dominicana", "Uruguay", "Venezuela", " " }));
        cmbPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaisItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 210, 30));

        cmbLocalidad.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cmbLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 500, 30));

        txtCalle.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 400, 390, 30));

        txtNumero.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 400, 90, 30));

        lblDni.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblDni.setText("DNI:");
        getContentPane().add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        txtNombre.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 510, 30));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 450, 360, 30));

        cmbProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProvinciaItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, 230, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        jButton1.setText("Atras");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 80, -1));

        lblApellido.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblApellido.setText("Apellido:");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 100, 30));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 250, 510, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
    System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    VistaGestionTecnico gestiontec = new VistaGestionTecnico();
    gestiontec.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    private void cmbPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaisItemStateChanged
        // TODO add your handling code here:
        try {
            String pais = cmbPais.getSelectedItem().toString();
            presentador.leerProvincias(pais);
        } catch(Exception e){
        }
    }//GEN-LAST:event_cmbPaisItemStateChanged

    private void cmbProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProvinciaItemStateChanged
        // TODO add your handling code here:
        try {
            String provincia = cmbProvincia.getSelectedItem().toString();
            presentador.leerLocalidades(provincia);
        } catch(Exception e){
        }
    }//GEN-LAST:event_cmbProvinciaItemStateChanged

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        try {
            long cuitProveedor = Long.parseLong(txtCUIT.getText());
            long dni = Long.parseLong(txtDni.getText());
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String calle = txtCalle.getText();
            int numero = Integer.parseInt(txtNumero.getText());
            String localidad = cmbLocalidad.getSelectedItem().toString();
            long telefono = Long.parseLong(txtTelefono.getText());
            String estado = cmbEstado.getSelectedItem().toString();
            
            presentador.registarTecnico(dni, cuitProveedor, nombre, apellido, calle, numero, localidad, telefono, estado);
        } catch(Exception e) {
            this.mostrarMje("Error en uno de los campos");
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaRegistroTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaRegistroTec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbLocalidad;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblCuit;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCUIT;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
