/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import interfaz.IGestionTecnicoMod;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import modelo.Domicilio;
import modelo.Estado;
import modelo.Localidad;
import modelo.Pais;
import modelo.Provincia;
import modelo.Tecnico;
import presentador.PresentadorGestorTecnicoMod;

/**
 *
 * @author USUARIO
 */
public class VistaModificarTec extends javax.swing.JFrame implements IGestionTecnicoMod{
    private PresentadorGestorTecnicoMod presentador;

    /**
     * Creates new form VistaRegistroPro
     */
    public VistaModificarTec() {
        initComponents();
        this.setLocationRelativeTo(null);
        presentador = new PresentadorGestorTecnicoMod(this);
        presentador.cargarListaPais();
        presentador.cargarListaEstado();
    }
    
    @Override
    public void cargarListaPais(ArrayList<Pais> paises) {
        cmbPais.removeAllItems();
        for(Pais pais : paises){
            cmbPais.addItem(pais.getNombre());
        }
        cmbPais.setSelectedIndex(0);
    }

    @Override
    public void cargarListaProvincia(ArrayList<Provincia> provincias) {
        cmbProvincia.removeAllItems();
        for(Provincia prov : provincias){
            cmbProvincia.addItem(prov.getNombre());
        }
        cmbProvincia.setSelectedIndex(0);
    }

    @Override
    public void cargarListaLocalidad(ArrayList<Localidad> localidades){
        cmbLocalidad.removeAllItems();
        for(Localidad l : localidades){
            cmbLocalidad.addItem(l.getNombre());
        }
        cmbLocalidad.setSelectedIndex(0);
    }
    
    @Override
    public void cargarListaEstado(ArrayList<Estado> estados){
        cmbEstado.removeAllItems();
        for(Estado est : estados){
            cmbEstado.addItem(est.getEstado());
        }
        cmbEstado.setSelectedIndex(0);
    }
    
    @Override
    public void mostrarMje(String mje){
        JOptionPane.showMessageDialog(null, mje);
    }
    
    public void buscarTecnico(long l) {
        presentador.buscarTecnico(l);
    }
    
    @Override
    public void llenarVistaConDatos(Tecnico tecnico, Estado estado, Domicilio domicilio, Localidad localidad){
        txtDni.setText(tecnico.getDNI()+"");
        cmbEstado.setSelectedItem(estado.getEstado());
        txtApellido.setText(tecnico.getApellido());
        txtNombre.setText(tecnico.getNombre());
        cmbLocalidad.setSelectedItem(localidad.getNombre());
        txtCalle.setText(domicilio.getCalle());
        txtNumero.setText(domicilio.getNumero()+"");
        txtTelefono.setText(tecnico.getTelefono()+"");
    }
    
    public void cerrar(){
        VistaGestionTecnico gestiontec = new VistaGestionTecnico();
        gestiontec.setVisible(true);
        this.dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblPais = new javax.swing.JLabel();
        lblProvincia = new javax.swing.JLabel();
        lblLocalidad = new javax.swing.JLabel();
        lblCalle = new javax.swing.JLabel();
        lblNumero = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        txtDni = new javax.swing.JTextField();
        cmbEstado = new javax.swing.JComboBox<>();
        cmbPais = new javax.swing.JComboBox<>();
        cmbLocalidad = new javax.swing.JComboBox<>();
        txtCalle = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        cmbProvincia = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();
        lblApellido = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/modificaciontec.png"))); // NOI18N
        getContentPane().add(lblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblDni.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblDni.setText("DNI:");
        getContentPane().add(lblDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 40, 30));

        lblEstado.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblEstado.setText("Estado:");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, -1, 30));

        lblNombre.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblNombre.setText("Apellido:");
        getContentPane().add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, -1, 40));

        lblPais.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblPais.setText("País:");
        getContentPane().add(lblPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, 40, 30));

        lblProvincia.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblProvincia.setText("Provincia:");
        getContentPane().add(lblProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, -1, 30));

        lblLocalidad.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblLocalidad.setText("Localidad:");
        getContentPane().add(lblLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, -1, 30));

        lblCalle.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblCalle.setText("Calle:");
        getContentPane().add(lblCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 380, -1, 30));

        lblNumero.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblNumero.setText("N°:");
        getContentPane().add(lblNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 40, 30));

        lblTelefono.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblTelefono.setText("Teléfono:");
        getContentPane().add(lblTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, -1, 30));

        btnRegistrar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegistrar.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 490, 130, -1));

        txtDni.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 240, 30));

        cmbEstado.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Habilitado", "Inhabilitado" }));
        getContentPane().add(cmbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, 210, 30));

        cmbPais.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cmbPais.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Argentina", "Bolivia", "Brasil", "Chile ", "Colombia", "Costa Rica ", "Cuba", "Ecuador", "El Salvador ", "Guatemala", "Honduras ", "México", "Nicaragua", "Panamá", "Paraguay", "Perú", "Puerto Rico", "República Dominicana", "Uruguay", "Venezuela", " " }));
        cmbPais.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaisItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 210, 30));

        cmbLocalidad.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        cmbLocalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbLocalidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 500, 30));

        txtCalle.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 390, 30));

        txtNumero.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, 90, 30));

        txtNombre.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 510, 30));
        getContentPane().add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 360, 30));

        cmbProvincia.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbProvinciaItemStateChanged(evt);
            }
        });
        getContentPane().add(cmbProvincia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 230, 30));

        btnSalir.setBackground(new java.awt.Color(147, 0, 0));
        btnSalir.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 560, 80, -1));

        btnAtras.setBackground(new java.awt.Color(153, 153, 153));
        btnAtras.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 16)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtrasMouseClicked(evt);
            }
        });
        getContentPane().add(btnAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 560, -1, -1));

        lblApellido.setFont(new java.awt.Font("Microsoft JhengHei Light", 1, 14)); // NOI18N
        lblApellido.setText("Nombre:");
        getContentPane().add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, 30));

        txtApellido.setFont(new java.awt.Font("Microsoft JhengHei Light", 0, 14)); // NOI18N
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 510, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
    System.exit(0);
    }//GEN-LAST:event_btnSalirMouseClicked

    private void btnAtrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtrasMouseClicked
    VistaGestionTecnico gestiontec = new VistaGestionTecnico();
    gestiontec.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnAtrasMouseClicked

    private void cmbPaisItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaisItemStateChanged
        // TODO add your handling code here:
        try {
            String pais = cmbPais.getSelectedItem().toString();
            presentador.leerProvincias(pais);
        } catch(Exception e){
        }
    }//GEN-LAST:event_cmbPaisItemStateChanged

    private void cmbProvinciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbProvinciaItemStateChanged
        // TODO add your handling code here:
        try {
            String provincia = cmbProvincia.getSelectedItem().toString();
            presentador.leerLocalidades(provincia);
        } catch(Exception e){
        }
    }//GEN-LAST:event_cmbProvinciaItemStateChanged

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked
        // TODO add your handling code here:
        try {
            long dni = Long.parseLong(txtDni.getText());
            String nombre = txtNombre.getText();
            String apellido = txtApellido.getText();
            String calle = txtCalle.getText();
            int numero = Integer.parseInt(txtNumero.getText());
            String localidad = cmbLocalidad.getSelectedItem().toString();
            long telefono = Long.parseLong(txtTelefono.getText());
            String estado = cmbEstado.getSelectedItem().toString();
            
            presentador.actualizarTecnico(dni, nombre, apellido, calle, numero, localidad, telefono, estado);
        } catch(Exception e) {
            this.mostrarMje("Error en uno de los campos");
        }
    }//GEN-LAST:event_btnRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaModificarTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaModificarTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaModificarTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaModificarTec.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaModificarTec().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbLocalidad;
    private javax.swing.JComboBox<String> cmbPais;
    private javax.swing.JComboBox<String> cmbProvincia;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblCalle;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLocalidad;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNumero;
    private javax.swing.JLabel lblPais;
    private javax.swing.JLabel lblProvincia;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables

   

    

    
}
